set(_CATKIN_CURRENT_PACKAGE "rospy")
set(rospy_VERSION "1.11.7")
set(rospy_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rospy_BUILD_DEPENDS )
set(rospy_RUN_DEPENDS "genpy" "python-numpy" "python-rospkg" "python-yaml" "roscpp" "rosgraph" "rosgraph_msgs" "roslib" "std_msgs")
set(rospy_DEPRECATED "")
set(rospy_BUILDTOOL_DEPENDS "catkin")
set(rospy_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")