set(rospy_SETUP_PY_VERSION "1.11.7")
set(rospy_SETUP_PY_SCRIPTS "")
set(rospy_SETUP_PY_PACKAGES "rospy")
set(rospy_SETUP_PY_PACKAGE_DIRS "src/rospy")
set(rospy_SETUP_PY_MODULES "")
set(rospy_SETUP_PY_MODULE_DIRS "")