# CMake generated Testfile for 
# Source directory: /home/ubuntu/ros_catkin_ws/src/ros/roslib
# Build directory: /home/ubuntu/ros_catkin_ws/build_isolated/roslib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_roslib_nosetests_test "/home/ubuntu/ros_catkin_ws/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/ubuntu/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/ubuntu/ros_catkin_ws/build_isolated/roslib/test_results/roslib/nosetests-test.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/ubuntu/ros_catkin_ws/build_isolated/roslib/test_results/roslib" "/usr/bin/nosetests-2.7 -P --process-timeout=60 --where=/home/ubuntu/ros_catkin_ws/src/ros/roslib/test --with-xunit --xunit-file=/home/ubuntu/ros_catkin_ws/build_isolated/roslib/test_results/roslib/nosetests-test.xml")
ADD_TEST(_ctest_roslib_gtest_roslib-utest "/home/ubuntu/ros_catkin_ws/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/ubuntu/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/ubuntu/ros_catkin_ws/build_isolated/roslib/test_results/roslib/gtest-roslib-utest.xml" "--working-dir" "/home/ubuntu/ros_catkin_ws/src/ros/roslib" "--return-code" "/home/ubuntu/ros_catkin_ws/devel_isolated/roslib/lib/roslib/roslib-utest --gtest_output=xml:/home/ubuntu/ros_catkin_ws/build_isolated/roslib/test_results/roslib/gtest-roslib-utest.xml")
ADD_TEST(_ctest_roslib_gtest_roslib-test_package "/home/ubuntu/ros_catkin_ws/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/ubuntu/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/ubuntu/ros_catkin_ws/build_isolated/roslib/test_results/roslib/gtest-roslib-test_package.xml" "--return-code" "/home/ubuntu/ros_catkin_ws/devel_isolated/roslib/lib/roslib/roslib-test_package --gtest_output=xml:/home/ubuntu/ros_catkin_ws/build_isolated/roslib/test_results/roslib/gtest-roslib-test_package.xml")
SUBDIRS(gtest)
