# CMake generated Testfile for 
# Source directory: /home/ubuntu/ros_catkin_ws/src/ros_comm/rostest
# Build directory: /home/ubuntu/ros_catkin_ws/build_isolated/rostest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_rostest_gtest_test_permuter "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/ubuntu/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/test_results/rostest/gtest-test_permuter.xml" "--return-code" "/home/ubuntu/ros_catkin_ws/devel_isolated/rostest/lib/rostest/test_permuter --gtest_output=xml:/home/ubuntu/ros_catkin_ws/build_isolated/rostest/test_results/rostest/gtest-test_permuter.xml")
ADD_TEST(_ctest_rostest_rostest_test_hztest0.test "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/ubuntu/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_hztest0.xml" "--return-code" "/home/ubuntu/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/ubuntu/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_hztest0.xml /home/ubuntu/ros_catkin_ws/src/ros_comm/rostest/test/hztest0.test ")
ADD_TEST(_ctest_rostest_rostest_test_hztest.test "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/ubuntu/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_hztest.xml" "--return-code" "/home/ubuntu/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/ubuntu/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_hztest.xml /home/ubuntu/ros_catkin_ws/src/ros_comm/rostest/test/hztest.test ")
ADD_TEST(_ctest_rostest_rostest_test_clean_master.test "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/ubuntu/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_clean_master.xml" "--return-code" "/home/ubuntu/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/ubuntu/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_clean_master.xml /home/ubuntu/ros_catkin_ws/src/ros_comm/rostest/test/clean_master.test ")
ADD_TEST(_ctest_rostest_rostest_test_distro_version.test "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/ubuntu/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/ubuntu/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_distro_version.xml" "--return-code" "/home/ubuntu/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/ubuntu/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_distro_version.xml /home/ubuntu/ros_catkin_ws/src/ros_comm/rostest/test/distro_version.test ")
SUBDIRS(gtest)
