#!/usr/bin/env python

import Adafruit_BBIO.GPIO as GPIO
import threading
import time
import sys

def threadfunc():
	while True:
		gauge("11000")
		time.sleep(.1)
		gauge("01100")
		time.sleep(.1)
		gauge("00110")
		time.sleep(.1)
		gauge("00011")
		time.sleep(.1)
		gauge("00110")
		time.sleep(.1)
		gauge("01100")
		time.sleep(.1)
	return
		

#Led_gauge(12345)
def gauge(str):
	if str[0]== '1':
		GPIO.output("P8_17", GPIO.HIGH) #1
	else:
		GPIO.output("P8_17", GPIO.LOW)
		
	if str[1]== '1':
		GPIO.output("P8_18", GPIO.HIGH) #2
	else:
		GPIO.output("P8_18", GPIO.LOW)
	
	if str[2]== '1':
		GPIO.output("P8_15", GPIO.HIGH) #3
	else:
		GPIO.output("P8_15", GPIO.LOW) 
	
	if str[3]== '1':
		GPIO.output("P8_16", GPIO.HIGH)#4
	else:
		GPIO.output("P8_16", GPIO.LOW)
		
	if str[4]== '1':
		GPIO.output("P8_14", GPIO.HIGH) #5
	else:
		GPIO.output("P8_14", GPIO.LOW) 
		
	return
	
GPIO.setup("P8_14", GPIO.OUT);
GPIO.setup("P8_15", GPIO.OUT);
GPIO.setup("P8_16", GPIO.OUT);
GPIO.setup("P8_17", GPIO.OUT);
GPIO.setup("P8_18", GPIO.OUT);

if sys.argv[1]== "-stop":
	gauge("00000")
else:
	th = threading.Thread(target=threadfunc)
	#th.daemon = True
	th.start()



