set(_CATKIN_CURRENT_PACKAGE "rostopic")
set(rostopic_VERSION "1.11.7")
set(rostopic_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rostopic_BUILD_DEPENDS "rostest")
set(rostopic_RUN_DEPENDS "rosbag" "rospy")
set(rostopic_DEPRECATED "")
set(rostopic_BUILDTOOL_DEPENDS "catkin")
set(rostopic_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")